services:

  backend:
    build: backend
    # restart: always
    ports:
     - 5000:5000
    environment:
      - MYSQL_HOST=db
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=final_project
    networks:
      - react-spring
      - spring-mysql
  
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=final_project
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./db/final_project_db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring-mysql

  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000:80
    volumes:
      - ./frontend/src:/code/src
      - ./frontend/public:/code/public
    networks:
      - react-spring
    depends_on:
      - backend
    expose:
      - 3306
      - 33060

volumes:
  db:
    driver: local

networks:
  react-spring: {}
  spring-mysql: {}
