CREATE DATABASE /*!32312 IF NOT EXISTS*/`final_project` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE final_project;

DROP TABLE IF EXISTS `people`;
CREATE TABLE people (
  `PersonID` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `FirstName` VARCHAR(255) NOT NULL,
  `LastName` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `items`;
CREATE TABLE items (
  `ItemID` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `orders`;
CREATE TABLE orders (
  `OrderID` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `PersonID` INT UNSIGNED NOT NULL,
  `OrderDate` DATETIME NOT NULL,
  FOREIGN KEY (PersonID) REFERENCES people (PersonID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `order_details`;
CREATE TABLE order_details (
  `OrderDetailsID` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `OrderID` INT UNSIGNED NOT NULL,
  `ItemID` INT UNSIGNED NOT NULL,
  `Quantity` INT,
  FOREIGN KEY (OrderID) REFERENCES orders (OrderID),
  FOREIGN KEY (ItemID) REFERENCES items (ItemID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

